cc_shared_library(
    name = "core",
    deps = ["//core"]
)

# cc_binary(
#     name = "app",
#     srcs = [
#         "main.cpp",
#     ],
#     linkopts = [
#         "-SUBSYSTEM:WINDOWS",
#         "User32.lib",
#     ],
#     deps = ["//core"],
# )
