workspace(name = "ciart-studio")

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:local.bzl", "local_repository")

# Skia
git_repository(
    name = "skia",
    branch = "chrome/m129",
    remote = "https://skia.googlesource.com/skia.git",
)

local_repository(
    name = "skia_user_config",
    path = "custom_skia_config",
)

load("@skia//bazel:deps.bzl", "bazel_deps", "c_plus_plus_deps", "header_based_configs")

bazel_deps()

c_plus_plus_deps()

header_based_configs()
